<?php

/* This file is was automatically generated. */
namespace Krak\Fn;

const method = 'Krak\\Fn\\method';
const prop = 'Krak\\Fn\\prop';
const index = 'Krak\\Fn\\index';
const propIn = 'Krak\\Fn\\propIn';
const indexIn = 'Krak\\Fn\\indexIn';
const hasIndexIn = 'Krak\\Fn\\hasIndexIn';
const updateIndexIn = 'Krak\\Fn\\updateIndexIn';
const takeWhile = 'Krak\\Fn\\takeWhile';
const dropWhile = 'Krak\\Fn\\dropWhile';
const take = 'Krak\\Fn\\take';
const drop = 'Krak\\Fn\\drop';
const slice = 'Krak\\Fn\\slice';
const head = 'Krak\\Fn\\head';
const chunk = 'Krak\\Fn\\chunk';
const range = 'Krak\\Fn\\range';
const op = 'Krak\\Fn\\op';
const andf = 'Krak\\Fn\\andf';
const orf = 'Krak\\Fn\\orf';
const chain = 'Krak\\Fn\\chain';
const flatMap = 'Krak\\Fn\\flatMap';
const flatten = 'Krak\\Fn\\flatten';
const when = 'Krak\\Fn\\when';
const toPairs = 'Krak\\Fn\\toPairs';
const fromPairs = 'Krak\\Fn\\fromPairs';
const without = 'Krak\\Fn\\without';
const inArray = 'Krak\\Fn\\inArray';
const all = 'Krak\\Fn\\all';
const any = 'Krak\\Fn\\any';
const search = 'Krak\\Fn\\search';
const trans = 'Krak\\Fn\\trans';
const not = 'Krak\\Fn\\not';
const isInstance = 'Krak\\Fn\\isInstance';
const isNull = 'Krak\\Fn\\isNull';
const partition = 'Krak\\Fn\\partition';
const map = 'Krak\\Fn\\map';
const mapKeys = 'Krak\\Fn\\mapKeys';
const reduce = 'Krak\\Fn\\reduce';
const filter = 'Krak\\Fn\\filter';
const filterKeys = 'Krak\\Fn\\filterKeys';
const curry = 'Krak\\Fn\\curry';
const placeholder = 'Krak\\Fn\\placeholder';
const _ = 'Krak\\Fn\\_';
const partial = 'Krak\\Fn\\partial';
const autoCurry = 'Krak\\Fn\\autoCurry';
const toArray = 'Krak\\Fn\\toArray';
const toArrayWithKeys = 'Krak\\Fn\\toArrayWithKeys';
const id = 'Krak\\Fn\\id';
const pipe = 'Krak\\Fn\\pipe';
const compose = 'Krak\\Fn\\compose';
const stack = 'Krak\\Fn\\stack';
const onEach = 'Krak\\Fn\\onEach';