<?php

namespace Krak\Fun\Generate;

use PhpParser\{
    Comment,
    Node\Stmt\Function_,
    Node\Stmt\Namespace_,
    Node\Stmt\Return_,
    Node\Expr\Closure,
    Node\Expr\ClosureUse,
    Node\Expr\Variable,
    Node\Const_,
    Node\Stmt,
    Node\Param,
    BuilderHelpers
};
use function Krak\Fun\{
    toArray, filter, partition
};

/** @internal */
function createDocComment(): Comment\Doc {
    return new Comment\Doc("/* This file is automatically generated. */");
}

/** @internal */
function createConstFromFunc(Function_ $fn, Namespace_ $ns): Stmt\Const_ {
    if (!$ns->name) {
        throw new \RuntimeException('Cannot create constant for anonymous function.');
    }
    $constVal = $ns->name . '\\' . $fn->name;
    return new Stmt\Const_([
        new Const_($fn->name, BuilderHelpers::normalizeValue($constVal))
    ]);
}

/** @internal */
function curryFunction(Function_ $fn): Function_ {
    list($params, $optionalParams) = partition(function(Param $param) {
        /** @psalm-suppress MixedAssignment */
        $name = $param->var->name ?? null;
        if (!is_string($name)) {
            throw new \RuntimeException('Cannot curry function with non simple parameter names.');
        }
        return $param->default
            || ($param->variadic && strpos((string) $name, 'optional') === 0);
    }, $fn->params);

    // return all params but the first and reverse them
    $revParams = array_merge(array_reverse($params), $optionalParams);

    // if we have only one requried arg, then we allow zero required args in curried implementation
    $numParams = count($params) > 1 ? count($params) - 2 : count($params) - 1;
    $stmts = array_reduce(
        range(0, $numParams),
        /** @param Stmt[] $stmts */
        function($stmts, int $i) use ($revParams) {
        $remainingArgsForUse = array_slice($revParams, $i + 1);
        $curParam = $revParams[$i];
        return [new Return_(new Closure([
            'params' => [clone $curParam],
            'uses' => array_map(function($param) {
                if ($param->var instanceof Variable) {
                    return new ClosureUse(clone $param->var);
                } else {
                  throw new \RuntimeException('Expected params to be variables, not error type.');
                }
            }, $remainingArgsForUse),
            'stmts' => $stmts,
        ]))];
    }, $fn->getStmts());

    return new Function_($fn->name, [
        'params' => array_merge(
            count($params) > 1 ? [$params[0]] : [],
            $optionalParams
        ),
        'stmts' => $stmts,
    ]);
}

function isCurryable(Function_ $func): bool {
    if (in_array((string) $func->name, ['curry', 'autoCurry'])) {
        return false;
    }
    $numReqParams = count(toArray(filter(function(Param $param) {
        return $param->default === null;
    }, $func->params)));
    return $numReqParams > 1 || ($numReqParams == 1 && count($func->params) > 1);
}
